### ISSUE TITLE
Not working on 10.0.1 Panic occurred while running Atmosphere (latest)

### ISSUE THREAD

**Issue by CapnBio** [olliz0r/sys-botbase#18]
After installing sys-botbase on the latest atmosphere and 10.0.1 it crashes when I run any game. 

On the screen it shows me
Paninc occurred while running atmosphere.

Title ID: 010041544D530000
Error Desc: Std: :abort() (0xFFE)

Report saved to /atmosphere/fatal_error/report_0265b10f0.bin

I tried to upload the file here, it won't let me since github does not allow it.

**Comment by inspier** [comment]
You should be able to upload a zip file with the crash report. Also are you using macOS for accessing your SD card by any chance, if so this may be an archive bit problem.

**Comment by Prom-MT** [comment]
I'm getting this same issue when error launching Animal Crossing, after installing sys-botbase (with the zip) (clean installation of everything):

_Panic occurred while running Atmosphere.
Title ID: 010041544D530000
Error Desc: std::abort() (0xffe)_
[report_0299fd5c4.zip](https://github.com/olliz0r/sys-botbase/files/4531391/report_0299fd5c4.zip)

I'm on the latest files from sdsetup.com 
Switch version: 10.0.1, Animal Crossing version 1.2
Atmosphere (Kosmos)  (v0.11.1/v15.6)
Windows 10 Pro 64bit

I tried the Archive Bit fixes already.

**Comment by inspier** [comment]
Try a clean install of Atmosphere.

**Comment by inspier** [comment]
Try a clean install of Atmosphere from the release page instead.

**Comment by CapnBio** [comment]
I tried a clean atmosphere and hekate, thought that would actually help, I actually installed the latest atmosphere as well thinking that might fix it.
[report_0265b10f0.zip](https://github.com/olliz0r/sys-botbase/files/4535761/report_0265b10f0.zip)

**Comment by thelone3agle** [comment]
Having the same issues with the latest version of Atmosphere (12.0). Panics when loading the homebrew menu/launcher by clicking on the Album icon.

**Comment by inspier** [comment]
Are you on a system version below 6.0 if so that is an Atmosphere problem.

**Comment by aldone1** [comment]
I have same problem with Switch 10.0.1 emummc, latest atmosphere and other sys-modules disable.
 Title ID: 0100000000000004
Error Desc: std::abort() (0xffe)
[report_000000003ea67871.zip](https://github.com/olliz0r/sys-botbase/files/4550961/report_000000003ea67871.zip)

**Comment by lanerobertlane** [comment]
Same problem on Atmosphere 0.11.1 and Firmware 10.0.1, animal crossing 1.2 

Tried clean install of CFW which didn't resolve issue.

**Comment by inspier** [comment]
Are any of you using v1.3? If not try that as 1.4 has a number of bugs.

**Comment by lanerobertlane** [comment]
I just tested with v1.3 as suggested (was previously trying v1.4). It didn't resolve this issue. Same error message.

**Comment by mistercapitale** [comment]
I have the same issue as well with Animal Crossings v1.2. If you place sys-botbase in the necessary spot, it makes the Switch unable to run anything. Is there an alternative option? 

This has worked before but with the newest update done on the switch it wont allow anything to run.

**Comment by unooftng** [comment]
Animal Crossings v1.2 is not allowing me to inject anything correcting. I'm running the latest atmosphere and the latest NHSE. I placed the file in the correct spot, but i am not experiencing the same problem everyone else is. I just cannot properly read or write inventory in animal crossing.

**Comment by CapnBio** [comment]
Solved my issue, I had to disable idnmitm cfg, I disabled auto boot for it and now works fine, guess it was conflicting with each other. I disabled auto boot with the tesla menu and rebooted, installed sysbot and viola, works perfect now.
