### ISSUE TITLE
Examples for using L Control stick 

### ISSUE THREAD

**Issue by luongthomas** [olliz0r/sys-botbase#20]
Thank you for creating this useful tool. 

I was wondering if there was a way of using the L Control Stick, I didn't see an example for how to use it within the python script.

If you could explain how to use it that would be great!

Cheers

**Comment by olliz0r** [comment]
you can use
"setStick <LEFT/RIGHT> <x value> <y value>"
where x and y can range from -0x8000 to 0x7FFF

so for example neutral position on the left stick would be
"setStick LEFT 0x0 0x0"

putting the left stick all the way to the left would be 
"setStick LEFT -0x8000 0x0"

You'll have to play a bit with the values to see what works for you. The stick will stay in the position until you send a new position, so you might want to reset it to neutral every now and then.

**Comment by luongthomas** [comment]
Awesome thank you @olliz0r!
