### ISSUE TITLE
broken with atmosphere 0.13.0

### ISSUE THREAD

**Issue by Monotek18** [olliz0r/sys-botbase#24]
https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.13.0
```Please note: this is (unavoidably) a breaking change. System modules using atmosphere-libs will need to update to understand what firmware version they are running.```

**Comment by olliz0r** [comment]
should be fine, while ams-libs is still in the repo it is currently not used by the sysmodule

**Comment by Monotek18** [comment]
I get a fatal error when booting with this sysmodule, removing the sysmodule fixed this error.

I don't know if the issue is related to ams-libs

**Comment by theiconrichie** [comment]
i get the same issue

**Comment by olliz0r** [comment]
I just updated to ams 0.13.0 on my switch and using botbase 1.5 works without any problems here. Can you try updating to that botbase?

**Comment by Monotek18** [comment]
I don't have this issue anymore with botbase 1.5, thanks!
