### ISSUE TITLE
Crashes on Atmosphere 0.13.0 

### ISSUE THREAD

**Issue by Atomic646** [olliz0r/sys-botbase#26]
When installed on Atmosphere  0.13.0, opening hb apps crashes Atmosphere until sysbot files are removed from sd card.

**Comment by Shinyhunter2109** [comment]
Try updating to the latest atmosphere and Switch Firmware . After updating it should work as usual. I get no errors

**Comment by Atomic646** [comment]
Is was actually because I had too many sys modules running at the same time. Thanks though.
