### ISSUE TITLE
can't inject ek8 in example code

### ISSUE THREAD

**Issue by hshwang88** [olliz0r/sys-botbase#27]
I'm running sys-botbase on emuMMC and i don't use any other cheat homebrews like Edizon.
My game doesn't get ek8 data from toInject.ek8 files, all other function seems doing well tho,
so I think I have sth wrong in below line

sendCommand(s, f"poke 0x4293D8B0 0x{pokemonToInject}")

Could you give me a piece of advice?

**Comment by olliz0r** [comment]
the address 0x4293D8B0 is for a old update/patch for the game, the updated game uses a different address to inject. You can take a look at https://github.com/kwsch/SysBot.NET/blob/0f941a7c2604672e855aea4858003d1b94aadae3/SysBot.Pokemon/Structures/RAM/PokeDataOffsets.cs for a few of the offsets, the new "box1slot1" offset should be 0x4506d890

**Comment by hshwang88** [comment]
Got it. Thank you again about this wonderful program.
