### ISSUE TITLE
Compatibility issues with atmosphere 0.15.0

### ISSUE THREAD

**Issue by quizno4evah** [olliz0r/sys-botbase#29]
Anyone else having issues with running sys-botbase on the latest version of atmosphere? It seems to work fine on 0.14.4, but on 0.15.0, atmosphere crashes once I hit the switch home menu.

Any idea what might be causing the crash? My switch is currently on 10.2.0.

**Comment by olliz0r** [comment]
Are you sure it is botbase that is crashing? It could be too many custom sysmodules running at the same time (their memory is very limited). I'm not aware of any systemic issues with botbase on ams 0.15.0

**Comment by quizno4evah** [comment]
I don't think I have any other sysmodules running that I'm aware of aside from botbase, here's a screenshot of the error message if it helps any.

![52ADFD32-0B83-4855-8448-84DE1EFDA8A8](https://user-images.githubusercontent.com/74487754/99209712-a3a52500-2778-11eb-969b-a103c6b968b9.jpeg)

**Comment by quizno4evah** [comment]
Did some digging after your advice olliz0r. Turns out one of the modules I had installed had two different versions of it included. For some reason, it causes botbase to be the source of the error. Here's the module and the folders I found:

010000000007E51A
420000000007E51A

Deleting the first instance fixes the problem. For anyone wondering, this is related to the Tesla overlay module.
