### ISSUE TITLE
Don't have the 430000000000000B in atmosphere

### ISSUE THREAD

**Issue by kresellekey** [olliz0r/sys-botbase#3]
Hi! I'm running atmosphere version 0.10.2 but don't appear to have this folder to put the nsp in, any ideas of why and how to solve this?

**Comment by jiaaluo** [comment]
You would create the folder, this is a non-issue.

**Comment by kresellekey** [comment]
ah okay, will close the issue but would recommend changing the home page to say this, as reading made me and a couple others assume it was just there already
