### ISSUE TITLE
Controller not work V.12 nintendo OS - AMS M.19.0

### ISSUE THREAD

**Issue by sapycola** [olliz0r/sys-botbase#36]
it's not possibile to press button on sys-botbase 

Socket connect Joycon pro -> OK

action on BUTTONS -> KO

**Comment by FezVrasta** [comment]
I’m experiencing console crashes with the latest Atmosphere. Is this a known problem?

**Comment by berichan** [comment]
> I’m experiencing console crashes with the latest Atmosphere. Is this a known problem?

Are they related to sys-botbase in any way?

**Comment by FezVrasta** [comment]
> > I’m experiencing console crashes with the latest Atmosphere. Is this a known problem?
> 
> 
> 
> Are they related to sys-botbase in any way?

Yes they do happen exclusively when sys-botbase is enabled

**Comment by berichan** [comment]
Can you send a screenshot of your ams crash screen?

**Comment by sapycola** [comment]
Ok, last version sys-botbase work. Issue closed

**Comment by FezVrasta** [comment]
> Can you send a screenshot of your ams crash screen?

I'll send it today, thanks for the reply!

**Comment by FezVrasta** [comment]
@berichan I'm sorry, actually, the console completely freezes, but no error page shows up. What can I do to provide you with more details?
