### ISSUE TITLE
sys-botbase 1.8 crashes under Atmosphère 0.20.1

### ISSUE THREAD

**Issue by boocrypt** [olliz0r/sys-botbase#44]
If I start hbmenu, the switch crashes, after deleting sysbot hbmenu loads normal.

![IMG_3569](https://user-images.githubusercontent.com/74729797/131624001-474f64bb-b3e7-45ac-b03a-bd63384908b1.jpg)

**Comment by berichan** [comment]
You have too many sysmodules. Delete a few so you're not running out of memory

**Comment by boocrypt** [comment]
I’ve do so and you’re right, thank you for the solution.

**Comment by TheLastFractal** [comment]
> You have too many sysmodules. Delete a few so you're not running out of memory

How do I delete them if I can't boot into atmosphere?

**Comment by AnthonieZ87** [comment]
> How do I delete them if I can't boot into atmosphere?

SD card to computer, open SD card, open Switch Folder, remove unnecessary .nro files
