### ISSUE TITLE
Not working in game

### ISSUE THREAD

**Issue by q8naser92** [olliz0r/sys-botbase#5]
Hello, 

I have downloaded and installed the sys-botbase with atomsphere 10.3 and tested the controls on the home screen of the switch. Everything on the home screen is working great. However when i open a game (pokemon) and try the controls in the game i am getting a connection timeout.
Any ideas why this is happening?

**Comment by q8naser92** [comment]
I have tried other different games, the issue seems to occur whenever a game is entered regardless of which game it is. Is there any requirement that must be done in order to allow the bot to work in game?

**Comment by olliz0r** [comment]
Pokemon specifically disconnects you when you start the game, you have to either connect to the internet or connect to lan mode(not local mode) to be able to connect with your pc.

**Comment by q8naser92** [comment]
Your right, it connects after enabling the internet, however when i send test commands nothing is happening on the switch, any ideas?

**Comment by q8naser92** [comment]
When i send the commands after successfully connecting python server.

**Comment by wwwwwwzx** [comment]
Pokemon SWSH only accept one controller's input. Detach other controller(s) first.

**Comment by q8naser92** [comment]
I just have the normal joycon connected, however input is still being sent and no action are being executed.

**Comment by q8naser92** [comment]
its working now, i reinstalled the sysbot thanks alot for everything
