### ISSUE TITLE
not working with 14.0.0 1.3.0 atmmosphere

### ISSUE THREAD

**Issue by no2moloh** [olliz0r/sys-botbase#55]
error code 2021-0003 (0x615)
program: 43000000000000b

when launching atmosphere 1.3.0 pre-release

**Comment by q1378659137** [comment]
俺也一样

**Comment by UltraSyko** [comment]
Agreed

**Comment by purzer0** [comment]
Also agreed

**Comment by ELY3M** [comment]
might need to recompile.

**Comment by berichan** [comment]
We know of the issue, actively working on it but might be a while until libnx is stable to put out a stable sys-botbase release for 14.0.0

**Comment by fadedlamp42** [comment]
Just +1'ing here; error code 2021-0003 (0x615) on 14.0.0, hekate 5.7.2.

I understand this is a pretty major HOS release, but for us less familiar with the changes in this patch: how long might "a while" be? It's ultimately up to those maintainers, of course, but given the scale of the changes- rough estimate?

**Comment by berichan** [comment]
interim update posted to releases https://github.com/olliz0r/sys-botbase/releases
