### ISSUE TITLE
Pre release no good

### ISSUE THREAD

**Issue by chimel23** [olliz0r/sys-botbase#57]
Why is the pre release of 211 still causing my Switch to crash as soon as I get to the home menu if it supports 14.0?

**Comment by berichan** [comment]
Other issues may be present, it might not play well with other sysmodules or you may have installed incorrectly. Wait for a stable release if you are unable to get the interim version working.

**Comment by chimel23** [comment]
Ok. Yeah I have Edizon and Emuiibo. Just running Sysbot for Pokémon live inject and animal crossing

**Comment by berichan** [comment]
You can try backing up and removing the additional sysmodules temporarily and booting with only sys-botbase present to see if that solves the issue

**Comment by sapycola** [comment]
in your contents folder remove other modules.
(use only sys-botbase and sys-ftpd-light if use it) other modules KO.
Only this module all ok.

**Comment by chimel23** [comment]
It seems to work better without Emuiibo. 
![45469AF2-BBD5-41E1-9C7E-E6214E3259FA](https://user-images.githubusercontent.com/35353777/160220233-f4f0495f-e1e5-480c-af93-f670725214be.jpeg)

this is the error I got

**Comment by berichan** [comment]
Could possibly be due to too many fs sessions open, I'll take a look at it for stable release
