### ISSUE TITLE
sys-botbase crash in atmosphere1.3.0 (Firmware 14.0.0)

### ISSUE THREAD

**Issue by sir1st** [olliz0r/sys-botbase#58]
Error code 2021-0003 (0x615)
As long as enable the sys-botbase module, system crashes. Without this module, asmosphere worsk fine
![IMG_20220331_150853](https://user-images.githubusercontent.com/23466852/160998223-b69b979d-71f7-462e-9edf-11fd99f0c166.jpg)

**Comment by ACCELBURSTLink** [comment]
I had this issue too, it's could be caused by sysmodules, mods, and atmo patches

**Comment by EXO5KELETON** [comment]
Any update on when it will come out of Pre-Release for 14.1.0?

**Comment by Conan179** [comment]
@EXO5KELETON which prerelease? Atmos 1.3.1 is stable

**Comment by EXO5KELETON** [comment]
<img width="889" alt="CleanShot 2022-04-07 at 10 43 34@2x" src="https://user-images.githubusercontent.com/66844343/162171112-452757e3-23b7-451a-a6f8-71d242d4c7ff.png">

**Comment by EXO5KELETON** [comment]
Yes AMS is stable but current sysbot base isn't or at least in my experience. and I'm on latest HOS and AMS 1.3.1
