### ISSUE TITLE
V2.2 consistent startup crashes

### ISSUE THREAD

**Issue by DaWoblefet** [olliz0r/sys-botbase#60]
Unfortunately, the atmosphere logs don't say much, but this is on latest version 2.2 and happens on boot of any game. Please let me know how I can provide more information to assist.
[01650036665_430000000000000b.log](https://github.com/olliz0r/sys-botbase/files/8496759/01650036665_430000000000000b.log)

**Comment by berichan** [comment]
You have too many sysmodules and are running into the max sessions limit (2021-0003)

**Comment by DaWoblefet** [comment]
> You have too many sysmodules and are running into the max sessions limit (2021-0003)

Verifying this was it. Thank you very much!
