### ISSUE TITLE
Problem with FailValidate

### ISSUE THREAD

**Issue by datnguyen2195** [olliz0r/sys-botbase#61]
Hi, I have a problem with **FailValidate**, tried your provided tips in FAQ and Troubleshooting but the issue is still not solved, everything is updated. 
=>If that fails, you can turn off validation in the settings and try reading RAM again and see if you get the correct inventory values.=**Not working**
=>If you have plugins loaded, are using cheats=**Not working**
=>If you have an offset error... =**No Idea** 

(Actually, my first try was about 3-4 days ago and succeeded, but after I download and install a few tweaks I can not use it again, do I have to re-install fresh atmosphere? 

Thanks

**Comment by berichan** [comment]
This is unrelated to sys-botbase (did you mean to open an issue for another repo?)

>I download and install a few tweaks I can not use it again

These "tweaks" are likely shifting RAM for whatever game you're trying to live edit. Try booting the game while holding L so they aren't loaded or delete them first.
