### ISSUE TITLE
Failed to read NSP metadata

### ISSUE THREAD

**Issue by b3y0ndd34th** [olliz0r/sys-botbase#65]
When installing using Tinfoil or Goldleaf.

manually copied files to atmosphere folder, when launching the exefs.nsp I receive the same error.

I have updated Atmosphere, Tinfoil, and sigpatches.

**Comment by olliz0r** [comment]
You are not supposed to install the nsp. Dropping the folder from the zip onto your sd card will put all files in the correct sub folders to ensure atmosphere detects and boots sysbotbase automatically when you boot your switch.
