### ISSUE TITLE
Sending `click HOME` as first input does not actually click the HOME button

### ISSUE THREAD

**Issue by Fehniix** [olliz0r/sys-botbase#67]
As per title, running on the latest version of stock FW, HOS and sys-botbase. Sending the `click HOME` command, even after sending `detachController`, does not do much. It appears as though the `HdlsVirtualDevice` gets successfully attached however... and no result code appears to be different than zero.
I've been trying to debug this but to no avail.

Sending `click HOME` again works; I guess a solution to whomever needed to *really* send the `click HOME` command as the very first input would be to send it twice. Any idea as to why this might happen?

**Comment by berichan** [comment]
I did spend a while trying to look into this but it does seem this is just how the virtual controller behaves (you can test it by creating a non-sysmodule that uses virtual controller that calls a HOME button press and nothing will happen until the second one is pressed)

The best workaround is as you say, press the HOME button twice if that is the first input. I did try sending a HOME press when attaching the virtual controller but this will work the first time then actually read the HOME button press on subsequent attempt, but will work as expected if the switch went to sleep. This is too inconsistent a workaround so something better would likely need to be found.

**Comment by Fehniix** [comment]
Thank you for spending the time investigating the issue! I appreciate it.
There was a workaround available for my hyper-specific case fortunately, which was indeed "priming" the virtual controller with another game-neutral input. 

I'm guessing this can be closed as not planned: if the behaviour does not extend to any other input, I would safely assume the use cases in which the `HOME` button needs to be sent as the first input are relatively edge-leaning, and thus implementing a consistent workaround that needs probably considerable research would not be worth it, unless plenty of time were to be available... but it's rather scarce lately. :)

Thank you!

**Comment by berichan** [comment]
I'll add options for an unused button BIT(20) and the palma (poke ball plus) button with next release. These shouldn't do anything in the vast majority of games so might be useful as a dummy button + a somewhat reliable workaround.
