### ISSUE TITLE
[ Deleted ]

### ISSUE THREAD

**Issue by S8hUGqihmLURd0DP** [olliz0r/sys-botbase#82]
[ Deleted ]

**Comment by FlameSlap** [comment]
> Hello, is it possible to use this to start a game automatically? I'm working on a project that requires a game to be open and sometimes it crashes due to mods. Basically I want it to be able to tell if Smash Ultimate closed or if the Switch is on the home page, if one of these conditions is true it automatically starts Smash.

Op will deliver aaaaany minute now.

**Comment by Archius0** [comment]
> > Hello, is it possible to use this to start a game automatically? I'm working on a project that requires a game to be open and sometimes it crashes due to mods. Basically I want it to be able to tell if Smash Ultimate closed or if the Switch is on the home page, if one of these conditions is true it automatically starts Smash.
> 
> Op will deliver aaaaany minute now.

Soon, very soon. I will eventually get an answer to a question I have for a cancelled project!
