### ISSUE TITLE
Some events on Switch not being detected

### ISSUE THREAD

**Issue by bedgin** [olliz0r/sys-botbase#90]
With the Switch v19 release and latest (as of 10/15) versions of Atmosphere, Hekate, and sys-botbase installed, I noticed something that I thought I should report here. On my treasure island when automatically getting a new Dodo, the script now doesn't detect that my character has entered the airport. On my islands that have not upgraded you get a "Attempt to enter airport: Try :1" and then it immediately warps to the desk. (Because, I think, it detected that the character has successfully entered the airport.) On the updated switch it tries to enter the airport 7 times, walking the character up to the right like it never made it through the door. Finally, after the 7 attempts, it does warp to the desk and complete getting the new Dodo. 

Not sure root cause, and it's not a show-stopper for me, but I thought I'd report it in case it's an indicator of a potentially deeper issue. Thanks for all your hard work!!!!

**Comment by ELY3M** [comment]
Can you try latest atmosphere release?  atmosphere just released new release after your post.

**Comment by ELY3M** [comment]
I did test on updated switch and I am able to get dodo code in one try.   
Just make sure you get latest release zip from atmosphere github and update your atmosphere files.

**Comment by bedgin** [comment]
When I get back home after work (CST) I'll try it and let you know. TY

**Comment by berichan** [comment]
This seems to be related to timing changes that happened with 19.0.0, sys-botbase functions the same as it did before and it's up to the routine to adapt to things like textboxes showing up earlier than they should in certain games like ACNH. You can seek help for this on discord, it isn't related to sys-botbase.

**Comment by bedgin** [comment]
Just jumped on to close the loop and saw your reply. You are 100% correct. I just figured out that the version of SysBot-ACNH-Orders I was using was way out of date. Updating that fixed the problem. Sorry to take up your time, and thanks for your patience. :)
